name: increment-version-action
description: Create + push new tag based on calling repo's current version and version information in a metadata JSON file

inputs:
  json:
    description: Path to metadata JSON file containing version
    required: true
    default: repo-data.json
  token:
    description: Token with permissions to push tags, including against any tag protection rules
    required: false
    default: ${{ github.token }}

outputs:
  new-version:
    description: The newly tagged version
    value: ${{ steps.output-new-version.outputs.new-version }}


runs:
  using: composite
  steps:
    - name: Checkout calling repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ inputs.token }}
    - name: Pull tags down
      shell: bash
      run: git fetch origin --tags
    - name: Set up orf-utils
      uses: open-reading-frame/setup-python-action@main
      with:
        packages: orf_utils
    - name: Set up git user based on current action environment
      uses: fregante/setup-git-user@v1
    - name: Run tag_commit.py with given arguments - lays down a new tag or errors if specified version is invalid
      shell: bash
      run: |
        tag_commit \
          -r . \
          -j ${{ inputs.json }}
    - name: Set new-version output
      id: output-new-version
      shell: bash
      run: echo "new-version=$(git describe --tags)" >> $GITHUB_OUTPUT
    - name: Push new tag to GitHub - only runs when the calling workflow was triggered by a push event to default branch
      if: ${{ github.event_name == 'push' && github.ref_name == github.event.repository.default_branch }}
      shell: bash
      run: git push --tags
